# Generated by Django 5.2.6 on 2025-09-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
