# Generated by Django 5.2.6 on 2025-09-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_pokemon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='image',
        ),
    ]
